[package]
# "." is not allowed in crate names, but we want a friendlier name for the
# directory and spec file, so we override it below.
name = "kubernetes-1_31"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
package-name = "kubernetes-1.31"

[[package.metadata.build-package.external-files]]
url = "https://distro.eks.amazonaws.com/kubernetes-1-31/releases/4/artifacts/kubernetes/v1.31.0/kubernetes-src.tar.gz"
sha512 = "c19a550d7e998f967a307abfde0d060f69a520f4000ef054e8652f05ae925792fa254ce9df3be15255684573c4b61c02eb722b480f6791648783dac6b0ed4c50"

# RPM BuildRequires
[build-dependencies]
glibc = { path = "../glibc" }

# RPM Requires
[dependencies]
aws-signing-helper = { path = "../aws-signing-helper" }
ecr-credential-provider-1_31 = { path = "../ecr-credential-provider-1.31" }
static-pods = { path = "../static-pods" }
# `conntrack-tools`, `containerd` and `findutils` are only needed at runtime,
# and are pulled in by `release`.
# conntrack-tools = { path = "../conntrack-tools" }
# containerd = { path = "../containerd" }
# findutils = { path = "../findutils" }
