[package]
name = "ec2-identity-doc-user-data-provider"
version = "0.1.0"
authors = ["Zac Mrowicki <mrowicki@amazon.com>", "Sam Berning <bernings@amazon.com>"]
edition = "2021"
license = "Apache-2.0 OR MIT"
publish = false
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
async-trait.workspace = true
imdsclient.workspace = true
log.workspace = true
serde_json.workspace = true
snafu.workspace = true
tokio = { workspace = true, features = ["macros", "process", "rt-multi-thread"] }
early-boot-config-provider.workspace = true

[build-dependencies]
generate-readme.workspace = true
