[package]
name = "grep"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://mirrors.kernel.org/gnu/grep"

[[package.metadata.build-package.external-files]]
url = "https://mirrors.kernel.org/gnu/grep/grep-3.11.tar.xz"
sha512 = "f254a1905a08c8173e12fbdd4fd8baed9a200217fba9d7641f0d78e4e002c1f2a621152d67027d9b25f0bb2430898f5233dc70909d8464fd13d7dd9298e65c42"

[dependencies]
libpcre = { path = "../libpcre" }

[build-dependencies]
libpcre = { path = "../libpcre" }
glibc = { path = "../glibc" }
