[package]
name = "xfsprogs"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://mirrors.edge.kernel.org/pub/linux/utils/fs/xfs/xfsprogs/"

[[package.metadata.build-package.external-files]]
url = "http://kernel.org/pub/linux/utils/fs/xfs/xfsprogs/xfsprogs-6.9.0.tar.xz"
sha512 = "c597453759c400690810971f0b2daf0e4e22c74270b0f9800e2235da5e5c1383b59bc1176c5bba0023f74b623020fb51c62f0e98a74885cf3a8336e0b81c9023"

[build-dependencies]
glibc = { path = "../glibc" }
libinih = { path = "../libinih" }
liburcu = { path = "../liburcu" }
util-linux = { path = "../util-linux" }

# RPM Requires
[dependencies]
# none
