[package]
name = "microcode"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

# Check the two upstream repositories for the latest releases

[[package.metadata.build-package.external-files]]
url = "https://www.kernel.org/pub/linux/kernel/firmware/linux-firmware-20240909.tar.xz"
sha512 = "d1918364f9925291da722075cf2d038082a6b6b5c6d7e5ab8b0888c5e87563718934f493fe172db21608d6eace92ade5c519b5f50b1fc7f25a328e45be059142"

[[package.metadata.build-package.external-files]]
url = "https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/archive/refs/tags/microcode-20240813.tar.gz"
sha512 = "ba1fa7d9bed7d90756ea959f5878afca0deacc9b1e932a936a15d74a411b7efb6103a4af75dc3731d9cbb2e464439ce9a7d448f75bc6f38b616907ff6dec6ee3"
